/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Admin;

import Config.Session;
import LoginPage.login_page;
import blotter.blotter_dashboard;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Raven
 */
public class admin_dashboard extends javax.swing.JFrame {

    /** Creates new form admin_dashboard */
    public admin_dashboard() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();
        label_user = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        label_user1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        user3 = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        label_user2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();
        user6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Playbill", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ADMIN DASHBOARD");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        logout.setBackground(new java.awt.Color(0, 204, 204));
        logout.setFont(new java.awt.Font("Playbill", 0, 30)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOGOUT");
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 5, 105, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 870, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_icon (1) (1).png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 180));

        acc_name.setFont(new java.awt.Font("Playbill", 0, 24)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("Admin");
        jPanel3.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 430));

        label_user.setBackground(new java.awt.Color(204, 255, 255));
        label_user.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        label_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_userMouseExited(evt);
            }
        });
        label_user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        label_user.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        user1.setBackground(new java.awt.Color(204, 255, 255));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/many_users_icon (1).png"))); // NOI18N
        user1.setOpaque(true);
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user1MouseExited(evt);
            }
        });
        label_user.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 110));

        user2.setBackground(new java.awt.Color(204, 255, 255));
        user2.setFont(new java.awt.Font("Playbill", 0, 30)); // NOI18N
        user2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user2.setText("Users");
        user2.setOpaque(true);
        user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user2MouseExited(evt);
            }
        });
        label_user.add(user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));

        jPanel1.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 150, 150));

        label_user1.setBackground(new java.awt.Color(204, 255, 255));
        label_user1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        label_user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_user1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_user1MouseExited(evt);
            }
        });
        label_user1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        label_user1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        user3.setBackground(new java.awt.Color(204, 255, 255));
        user3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/many_users_icon (1).png"))); // NOI18N
        user3.setOpaque(true);
        user3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user3MouseExited(evt);
            }
        });
        label_user1.add(user3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 100));

        user4.setBackground(new java.awt.Color(204, 255, 255));
        user4.setFont(new java.awt.Font("Playbill", 0, 30)); // NOI18N
        user4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user4.setText("Citizens");
        user4.setOpaque(true);
        user4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user4MouseExited(evt);
            }
        });
        label_user1.add(user4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));

        jPanel1.add(label_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 150, 150));

        label_user2.setBackground(new java.awt.Color(204, 255, 255));
        label_user2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        label_user2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_user2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_user2MouseExited(evt);
            }
        });
        label_user2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        label_user2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        user5.setBackground(new java.awt.Color(204, 255, 255));
        user5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/many_users_icon (1).png"))); // NOI18N
        user5.setOpaque(true);
        user5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user5MouseExited(evt);
            }
        });
        label_user2.add(user5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 100));

        user6.setBackground(new java.awt.Color(204, 255, 255));
        user6.setFont(new java.awt.Font("Playbill", 0, 30)); // NOI18N
        user6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user6.setText("Blotter");
        user6.setOpaque(true);
        user6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user6MouseExited(evt);
            }
        });
        label_user2.add(user6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));

        jPanel1.add(label_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 150, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Confirm Exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Exited Successfully!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Exit Canceled!");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Session sess = Session.getInstance();
        
        if(sess.getUid()==0){
            JOptionPane.showMessageDialog(null, "No account, Login First!");
            login_page lp = new login_page();
            lp.setVisible(true);
            this.dispose();
        }else{
            acc_name.setText(""+sess.getFname()+" "+sess.getLname());
        }
    }//GEN-LAST:event_formWindowActivated

    private void user1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user1MouseEntered

    private void user2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user2MouseEntered

    private void label_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_userMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_userMouseEntered

    private void user1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user1MouseExited

    private void user2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user2MouseExited

    private void label_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_userMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_userMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        user1.setForeground(Color.white);
        user1.setBackground(Color.gray);
        user2.setForeground(Color.white);
        user2.setBackground(Color.gray);
        label_user.setForeground(Color.white);
        label_user.setBackground(Color.gray);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        user1.setForeground(Color.black);
        user1.setBackground(null);
        user2.setForeground(Color.black);
        user2.setBackground(null);
        label_user.setForeground(Color.black);
        label_user.setBackground(null);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        user_form uf = new user_form();
        uf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int log = JOptionPane.showConfirmDialog(null, "Continue Logout?", "loginout", JOptionPane.YES_NO_OPTION);
        if(log == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Logout Successfully!");
            login_page lp = new login_page();
            lp.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Cancel Logout!");
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setForeground(Color.black);
        logout.setBackground(Color.white);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setForeground(Color.white);
        logout.setBackground(null);
    }//GEN-LAST:event_logoutMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        citizen_form cf = new citizen_form();
        cf.Uidentifier.setText("Admin");
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        user3.setForeground(Color.white);
        user3.setBackground(Color.gray);
        user4.setForeground(Color.white);
        user4.setBackground(Color.gray);
        label_user1.setForeground(Color.white);
        label_user1.setBackground(Color.gray);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        user3.setForeground(Color.black);
        user3.setBackground(null);
        user4.setForeground(Color.black);
        user4.setBackground(null);
        label_user1.setForeground(Color.black);
        label_user1.setBackground(null);
    }//GEN-LAST:event_jLabel3MouseExited

    private void user3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user3MouseEntered

    private void user3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user3MouseExited

    private void user4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user4MouseEntered

    private void user4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user4MouseExited

    private void label_user1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_user1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_user1MouseEntered

    private void label_user1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_user1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_user1MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        blotter_dashboard bd = new blotter_dashboard();
        bd.Uidentifier.setText("Admin");
        bd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        user5.setForeground(Color.white);
        user5.setBackground(Color.gray);
        user6.setForeground(Color.white);
        user6.setBackground(Color.gray);
        label_user2.setForeground(Color.white);
        label_user2.setBackground(Color.gray);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        user5.setForeground(Color.black);
        user5.setBackground(null);
        user6.setForeground(Color.black);
        user6.setBackground(null);
        label_user2.setForeground(Color.black);
        label_user2.setBackground(null);
    }//GEN-LAST:event_jLabel4MouseExited

    private void user5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user5MouseEntered

    private void user5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user5MouseExited

    private void user6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user6MouseEntered

    private void user6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user6MouseExited

    private void label_user2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_user2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_user2MouseEntered

    private void label_user2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_user2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_label_user2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel label_user;
    private javax.swing.JPanel label_user1;
    private javax.swing.JPanel label_user2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    private javax.swing.JLabel user6;
    // End of variables declaration//GEN-END:variables

}
