/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import CRUD_Form.crud_form_citizen;
import Config.Session;
import Config.config;
import LoginPage.login_page;
import User.user_dashboard;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Raven
 */
public class citizen_form extends javax.swing.JFrame {

    /**
     * Creates new form citizen_form
     */
    public citizen_form() {
        initComponents();
        displayData();
    }
    public void displayData(){
        try{
            config conf = new config();
            ResultSet rs = conf.getData("SELECT c_id, fname, lname, gender, birth_date, status FROM citizen");
            users_table.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        Uidentifier = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        acc_name = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        c_user_uid = new javax.swing.JLabel();
        c_user = new javax.swing.JLabel();
        Add = new javax.swing.JLabel();
        Edit = new javax.swing.JLabel();
        Delete = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Playbill", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CITIZEN FORM");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Playbill", 0, 30)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 5, 105, 50));

        Uidentifier.setFont(new java.awt.Font("Playbill", 1, 48)); // NOI18N
        Uidentifier.setForeground(new java.awt.Color(255, 255, 255));
        Uidentifier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Uidentifier.setText("Idintifier");
        jPanel2.add(Uidentifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 250, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 870, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_name.setFont(new java.awt.Font("Playbill", 0, 24)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("CITIZEN");
        jPanel3.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 30));

        user1.setBackground(new java.awt.Color(153, 255, 255));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/many_users_icon (1).png"))); // NOI18N
        user1.setOpaque(true);
        user1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user1MouseExited(evt);
            }
        });
        jPanel3.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 100));

        c_user_uid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_user_uid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c_user_uid.setText("ID");
        jPanel3.add(c_user_uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 30));

        c_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c_user.setText("Current User");
        jPanel3.add(c_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, 30));

        Add.setBackground(new java.awt.Color(153, 255, 255));
        Add.setFont(new java.awt.Font("Playbill", 0, 36)); // NOI18N
        Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add.setText("Add");
        Add.setOpaque(true);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        jPanel3.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 200, 210, 30));

        Edit.setBackground(new java.awt.Color(153, 255, 255));
        Edit.setFont(new java.awt.Font("Playbill", 0, 36)); // NOI18N
        Edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edit.setText("Edit");
        Edit.setOpaque(true);
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditMouseExited(evt);
            }
        });
        jPanel3.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 240, 210, 30));

        Delete.setBackground(new java.awt.Color(153, 255, 255));
        Delete.setFont(new java.awt.Font("Playbill", 0, 36)); // NOI18N
        Delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Delete.setText("Delete");
        Delete.setOpaque(true);
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMouseExited(evt);
            }
        });
        jPanel3.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 280, 210, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 430));

        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(users_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 610, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        if(Uidentifier.getText().equals("Admin")){
            admin_dashboard ad = new admin_dashboard();
            ad.setVisible(true);
            this.dispose();
        }else{
            user_dashboard ud = new user_dashboard();
            ud.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setForeground(Color.black);
        back.setBackground(Color.white);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setForeground(Color.white);
        back.setBackground(null);
    }//GEN-LAST:event_backMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Confirm Exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Exited Successfully!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Exit Canceled!");
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void user1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_user1MouseEntered

    private void user1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_user1MouseExited

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        // TODO add your handling code here:
        if(!Add.isEnabled()){
            return;
        }else{
            crud_form_citizen cf = new crud_form_citizen();
            cf.cid.setEnabled(false);
            cf.title.setText("Adding Citizen Form");
            cf.enter.setText("Add");
            cf.setVisible(true);
            cf.Select.setEnabled(true);
            cf.Remove.setEnabled(false);
            this.dispose();
        }
    }//GEN-LAST:event_AddMouseClicked

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        // TODO add your handling code here:
        Add.setForeground(Color.white);
        Add.setBackground(Color.gray);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        // TODO add your handling code here:
        Add.setForeground(Color.black);
        Add.setBackground(null);
    }//GEN-LAST:event_AddMouseExited

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        // TODO add your handling code here:
        if(!Edit.isEnabled()){
            return;
        }else{
            int rowIndex = users_table.getSelectedRow();
            if(rowIndex < 0){
                JOptionPane.showMessageDialog(null, "Please select an item!");
            }else{
                crud_form_citizen cf = new crud_form_citizen();
                try{
                    config conf = new config();
                    TableModel tbl = users_table.getModel();
                    ResultSet rs = conf.getData("Select * From citizen Where c_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
                    if(rs.next()){
                        cf.cid.setEnabled(false);
                        cf.cid.setText(""+rs.getInt("c_id"));
                        cf.fname.setText(""+rs.getString("fname"));
                        cf.lname.setText(""+rs.getString("lname"));
                        cf.gender.setSelectedItem(""+rs.getString("gender"));
                        cf.status.setSelectedItem(""+rs.getString("status"));
                        cf.enter.setText("Update");
                        cf.title.setText("Updating Citizen Form");
                        cf.image.setIcon(cf.ResizeImage(rs.getString("image"), null, cf.image));
                        cf.oldpath = rs.getString("image");
                        cf.path = rs.getString("image");
                        cf.destination = rs.getString("image");
                        cf.setVisible(true);

                        if(rs.getString("image").isEmpty()){
                            cf.Select.setEnabled(true);
                            cf.Remove.setEnabled(false);
                        }else{
                            cf.Select.setEnabled(false);
                            cf.Remove.setEnabled(true);
                        }

                        this.dispose();
                    }
                }catch(SQLException ex){
                    System.out.println(""+ex);
                }
            }
        }
    }//GEN-LAST:event_EditMouseClicked

    private void EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseEntered
        // TODO add your handling code here:
        Edit.setForeground(Color.white);
        Edit.setBackground(Color.gray);
    }//GEN-LAST:event_EditMouseEntered

    private void EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseExited
        // TODO add your handling code here:
        Edit.setForeground(Color.black);
        Edit.setBackground(null);
    }//GEN-LAST:event_EditMouseExited

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
        if (!Delete.isEnabled()) {
            return;
        } else {
            int rowIndex = users_table.getSelectedRow();
            if (rowIndex < 0) {
                JOptionPane.showMessageDialog(null, "Please select an item!");
            } else {
                try {
                    config conf = new config();
                    TableModel tbl = users_table.getModel();
                    String c_id = tbl.getValueAt(rowIndex, 0).toString();
                    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this user?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                        String sql = "DELETE FROM citizen WHERE c_id = '" + c_id + "'";
                        conf.deleteData(sql);
                        Session sess = Session.getInstance();
                        String action = "Deleted citizen with ID No. " + c_id;
                        conf.insertData("INSERT INTO logs (u_id, action, date) VALUES ('" + sess.getUid() + "', '" + action + "', '" + LocalDateTime.now() + "')");
                        displayData();
                    }
                } catch (Exception ex) {
                    System.out.println("Error: " + ex.getMessage());
                }
            }
        }

    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseEntered
        // TODO add your handling code here:
        Delete.setForeground(Color.white);
        Delete.setBackground(Color.gray);
    }//GEN-LAST:event_DeleteMouseEntered

    private void DeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseExited
        // TODO add your handling code here:
        Delete.setForeground(Color.black);
        Delete.setBackground(null);
    }//GEN-LAST:event_DeleteMouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Session sess = Session.getInstance();
        
        if(sess.getUid()==0){
            JOptionPane.showMessageDialog(null, "No account, Login First!");
            login_page lp = new login_page();
            lp.setVisible(true);
            this.dispose();
        }else{
            c_user_uid.setText(""+sess.getUid());
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(citizen_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(citizen_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(citizen_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(citizen_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new citizen_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Add;
    public javax.swing.JLabel Delete;
    public javax.swing.JLabel Edit;
    public javax.swing.JLabel Uidentifier;
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel back;
    private javax.swing.JLabel c_user;
    private javax.swing.JLabel c_user_uid;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel user1;
    private javax.swing.JTable users_table;
    // End of variables declaration//GEN-END:variables
}
