/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD_Form;

import Config.Session;
import Config.config;
import Config.passwordHasher;
import LoginPage.login_page;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Raven
 */
public class forgot_pass extends javax.swing.JFrame {

    /**
     * Creates new form forgot_pass
     */
    public forgot_pass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        cpassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        enter = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        fanimal = new javax.swing.JTextField();
        fcolor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Playbill", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("User Form");
        title.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 560, 40));

        email.setBackground(new java.awt.Color(204, 255, 255));
        email.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        email.setToolTipText("");
        email.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Enter User Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailMouseExited(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 610, 40));

        cpassword.setBackground(new java.awt.Color(204, 255, 255));
        cpassword.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cpassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Confirm Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanel1.add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 440, 40));

        password.setBackground(new java.awt.Color(204, 255, 255));
        password.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Enter New Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 440, 40));

        enter.setBackground(new java.awt.Color(204, 255, 255));
        enter.setFont(new java.awt.Font("Playbill", 0, 36)); // NOI18N
        enter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enter.setText("Enter");
        enter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        enter.setOpaque(true);
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterMouseExited(evt);
            }
        });
        jPanel1.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 90, 40));

        clear.setBackground(new java.awt.Color(204, 255, 255));
        clear.setFont(new java.awt.Font("Playbill", 0, 36)); // NOI18N
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("Clear");
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        clear.setOpaque(true);
        clear.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                clearMouseDragged(evt);
            }
        });
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clearMousePressed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 90, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 30, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        back.setBackground(new java.awt.Color(204, 255, 255));
        back.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 20));

        fanimal.setBackground(new java.awt.Color(204, 255, 255));
        fanimal.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fanimal.setToolTipText("");
        fanimal.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Favorite Animal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        fanimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fanimalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fanimalMouseExited(evt);
            }
        });
        fanimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fanimalActionPerformed(evt);
            }
        });
        jPanel1.add(fanimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, 40));

        fcolor.setBackground(new java.awt.Color(204, 255, 255));
        fcolor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fcolor.setToolTipText("");
        fcolor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Favorite Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        fcolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fcolorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fcolorMouseExited(evt);
            }
        });
        fcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcolorActionPerformed(evt);
            }
        });
        jPanel1.add(fcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseEntered

    private void emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseExited

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseClicked
        // TODO add your handling code here:
    config conf = new config();
        if(email.getText().isEmpty()
            || fanimal.getText().isEmpty()
            || fcolor.getText().isEmpty()
            || password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All Fields are Required!");
        } else if (password.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password Must be longer than 8!");
        } else if (!(password.getText().equals(cpassword.getText()))) {
            JOptionPane.showMessageDialog(null, "Password does not match!");
        } else {
            try {
                String query1 = "SELECT fcolor FROM accounts WHERE email = '"+email.getText()+"'";
                String query2 = "SELECT fanimal FROM accounts WHERE email = '"+email.getText()+"'";
                ResultSet rs1 = conf.getData(query1);
                ResultSet rs2 = conf.getData(query2);
                String color = "", animal = "";
                if(rs1.next()) {
                    color = rs1.getString("fcolor");
                }
                if(rs2.next()) {
                    animal = rs2.getString("fanimal");
                }
                if(!(fanimal.getText().equals(animal) && fcolor.getText().equals(color))) {
                    System.out.println(""+color);
                    System.out.println(""+animal);
                    JOptionPane.showMessageDialog(null, "Incorrect Information!\nTry Again!");
                } else {
                    try {
                        String pass = passwordHasher.hashPassword(password.getText());
                        conf.updateData("UPDATE accounts SET pname = '"+pass+"' WHERE email = '"+email.getText()+"'");
                        Session sess = Session.getInstance();
                        String action = "Reset password for account with email: " + email.getText();
                        conf.insertData("INSERT INTO logs (u_id, action, date) VALUES ('" + sess.getUid() + "', '" + action + "', '" + LocalDateTime.now() + "')");
                        login_page lp = new login_page();
                        lp.setVisible(true);
                        this.dispose();
                    } catch (NoSuchAlgorithmException ex) {
                        System.out.println(""+ex);
                    }
                }
            } catch (SQLException ex) {
                System.out.println("Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_enterMouseClicked

    private void enterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseEntered
        // TODO add your handling code here:
        enter.setForeground(Color.white);
        enter.setBackground(Color.gray);
    }//GEN-LAST:event_enterMouseEntered

    private void enterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseExited
        // TODO add your handling code here:
        enter.setForeground(Color.black);
        enter.setBackground(null);
    }//GEN-LAST:event_enterMouseExited

    private void clearMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseDragged

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // TODO add your handling code here:
        email.setText(null);
        fanimal.setText(null);
        fcolor.setText(null);
        password.setText(null);
        cpassword.setText(null);
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        clear.setForeground(Color.white);
        clear.setBackground(Color.gray);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
        clear.setForeground(Color.black);
        clear.setBackground(null);
    }//GEN-LAST:event_clearMouseExited

    private void clearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Confirm Exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Exited Successfully!");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Exit Canceled!");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        login_page lp = new login_page();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        back.setForeground(Color.white);
        back.setBackground(Color.gray);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        // TODO add your handling code here:
        back.setForeground(Color.black);
        back.setBackground(null);
    }//GEN-LAST:event_backMouseExited

    private void fanimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fanimalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_fanimalMouseEntered

    private void fanimalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fanimalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_fanimalMouseExited

    private void fanimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fanimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fanimalActionPerformed

    private void fcolorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcolorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_fcolorMouseEntered

    private void fcolorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcolorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_fcolorMouseExited

    private void fcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcolorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel clear;
    public javax.swing.JPasswordField cpassword;
    public javax.swing.JTextField email;
    public javax.swing.JLabel enter;
    public javax.swing.JTextField fanimal;
    public javax.swing.JTextField fcolor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPasswordField password;
    public javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
